dependencies {
    elytraModpackVersion {
        // 在这配置的gtnh版本 用于自动拉取依赖版本
        gtnhVersion = "2.9.0-beta-3"
        // 是否不缓存拉取的依赖清单文件
        manifestNoCache = false
        // 是否自动为输出的jar添加 `gtnhVersion` 后缀
        attachManifestVersionToJar = false
    }
//Write deps here
    //Placeholder







}

@SuppressWarnings('GrMethodMayBeStatic')
String gtnhDev(String name, String classifier = "dev") {
    return elytraModpackVersion.gtnh(name, classifier)
}

