// Add any additional repositories for your dependencies here.

repositories { handler ->
    // JBullet 与 vecmath 只在 Maven Central 上发布。
    mavenCentral()

    exclusiveContent {
        forRepository {
            handler.maven {
                name = 'glease'
                url = 'https://maven.glease.net/repos/releases/'
            }
        }
        filter {
            includeGroup('net.glease')
        }
    }
}
